export { default as Home } from './Home'
export { default as Page } from './Page'
export { default as Projects } from './Projects'
export { default as Education } from './Education'
export { default as ErrorPage } from './ErrorPage'
export { default as Contact } from './Contact'
